# Generated by Django 5.2.7 on 2025-10-27 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("universities", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="domain_verified",
            field=models.BooleanField(
                default=False, help_text="Email domain was found in university database"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="requires_admin_verification",
            field=models.BooleanField(
                default=False,
                help_text="Email domain not recognized, requires admin approval",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="validated_university",
            field=models.ForeignKey(
                blank=True,
                help_text="University auto-detected from email domain",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="universities.university",
            ),
        ),
    ]
