# Generated by Django 5.2.7 on 2025-10-27 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="University",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Official university name", max_length=300
                    ),
                ),
                ("country", models.CharField(default="United States", max_length=100)),
                (
                    "state_province",
                    models.CharField(
                        blank=True,
                        help_text="State or province (if available)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "alpha_two_code",
                    models.CharField(
                        default="US",
                        help_text="ISO 3166-1 alpha-2 country code",
                        max_length=2,
                    ),
                ),
                (
                    "web_pages",
                    models.TextField(
                        blank=True,
                        help_text="Comma-separated list of official web pages",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "University",
                "verbose_name_plural": "Universities",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name"], name="universitie_name_504812_idx"),
                    models.Index(
                        fields=["country"], name="universitie_country_a1a531_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UniversityDomain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        db_index=True,
                        help_text="Email domain (e.g., 'nyu.edu')",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Is this the primary domain for the university?",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "university",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domains",
                        to="universities.university",
                    ),
                ),
            ],
            options={
                "verbose_name": "University Domain",
                "verbose_name_plural": "University Domains",
                "ordering": ["-is_primary", "domain"],
                "indexes": [
                    models.Index(
                        fields=["domain"], name="universitie_domain_4140e8_idx"
                    ),
                    models.Index(
                        fields=["university", "is_primary"],
                        name="universitie_univers_7d10a2_idx",
                    ),
                ],
            },
        ),
    ]
